services:
  flask:
    build:
      context: .
      dockerfile: flask.Dockerfile
    ports:
      - "5000:5000"
    networks:
      - flask-net
    environment:
      - FLASK_APP=app.py
    command: python app.py  # Start Flask directly
    volumes:
      - flask_data:/app/holdings  # Use the shared volume
    restart: unless-stopped 

  email:
    image: stock-tracker
    container_name: email-service
    restart: unless-stopped
    volumes:
      - flask_data:/app/holdings  # Use the same shared volume
    environment:
      - SENDGRID_API_KEY=placeholder
    networks:
      - flask-net

networks:
  flask-net:
    driver: bridge

volumes:
  flask_data:  # Define a shared volume to store data
